### ISSUE TITLE
Allow the app to use external SD cards to store wiki databases

### ISSUE THREAD

**Issue by logomancer** [conchyliculture/wikipoff#11]
I have the English wiki on my tablet's SD card because there's more space there than the internal storage. However, WikipOff doesn't check there for databases. It would be nice if there was a way to designate a different directory for wikis.

**Comment by conchyliculture** [comment]
Fixed as of release [v0.3.0](https://github.com/conchyliculture/wikipoff/releases/tag/v0.3.0)
