### ISSUE TITLE
Downloading Wiki database from outside of app

### ISSUE THREAD

**Issue by jwalantsoneji** [conchyliculture/wikipoff#12]
Is there a way to download the required 7GB file from my desktop?
This would help in completing full download in 1 shot.

**Comment by jwalantsoneji** [comment]
the link given above is broken: https://github.com/conchyliculture/wikipoff/blob/master/assets/available_wikis.xml
Correct link is: https://github.com/conchyliculture/wikipoff/blob/external/assets/available_wikis.xml

**Comment by conchyliculture** [comment]
Oh, indeed!  I'll fix it in other places.
Thanks!

**Comment by conchyliculture** [comment]
The links inside the app will be fixed in next release. In the mean time I've put the file back at its previous place.
