### ISSUE TITLE
Support for other Wikis

### ISSUE THREAD

**Issue by ghost** [conchyliculture/wikipoff#15]
Forgive me if this is an ignorant question, but is it possible to support other Wikis such as [OpenStreetMap](https://wiki.openstreetmap.org/wiki/Main_Page)? In this case the wiki is much smaller than wikipedia, but images are more important and should be included if possible.

**Comment by conchyliculture** [comment]
The sister project [wikipoff-tools](https://github.com/conchyliculture/wikipoff-tools) is the tools which converts Wikipedia dumps into SQLite databases for WikipOff.
It supports MediaWiki 'code', so it would be able to convert any kind of MediaWIki dumps.
However, for database size (and smartphone space) issues, only text is converted, and a lot of stuff is discarded, like pictures. 
So it would support OpenStreetMap Wiki dumps to some extent (if they are available) but you'll lose the pictures.
